import 'package:firebase_auth/firebase_auth.dart';
import 'package:our_cabss/models/direction_details_info.dart';
import 'package:our_cabss/models/user_model.dart';

final FirebaseAuth firebaseAuth = FirebaseAuth.instance;
User? currentUser;
UserModel? userModelCurrentInfo;
DirectionDetailsInfo? tripDirectionDetailsInfo;

String claudMessagingServerToken =
    "key= ya29.c.c0ASRK0GZaYVJcUjxDGQKQMJ7slFE87pxyYIj9t8pGkC7acGWYjDW9E2dqHapcthDCJyXLLvF4B-slItZW9DuzdTBt9sUQ5OAxcqS6zG5hKQwRrp3d9E7RRpsN6FiodpuZF1hS4h7FoautqadiTBdk65_GREifVy6NO_U_bkcIHtxwudlsmVOa8ifDB-xklvuTgj9j2C1dB_XA2pAwpwVn_ndK2b6WlzQj2vokTE8bq2ltn-QZCIYs4kx2RybY-ucdTSxyfFYkWAtCPmEgVCLyzaCUoxo7RiO-6IicqwOvIt8QfEaAitwHlV8NksRAU8ATg54hiSY2W4DnIkmMudqMjDUBLbqByWw3sPcNsXKCEWpyFv_iPPXMmrCrRwE387PI2QIjUkZOXhZm4YdYgn9_WIyfUhje02ZQ9dSXhYcd4ZxXsxt4Q-2ur42n_RsUefiV08zaff_nF0zglRdjhbsVBf501zz9t7-SyeFfcW4Wfdi1fQ1SOp--6m1taeegXv8ifFI0R2d37k7Xa25yXY82tivY2ZXe9xhxgxhnW8kSlpzcnUWF5nj5chQQ1Xlaf8q2oUl3FwYpO65ci5FIdBggU1WVxm0mcW62FFIjjxip2nvRzQUw8Znwbs2h-4bo6egrwOumicquoFRFJb9qUa3IBvJItghcWvdOlhssmuFyVpRBUokJvkauyai1XM19ugXqXuUXemJ_hOBQh_mvq5g3j7x7gqbV3RuIvOdzkOkzsgjtQV8YlaZsXf2OuwUh4czjRdhBFj9ojJXw8YIWJbkojUtb-VOF0tjSJziRyJI4gvYcaUuw7sRw1jU1i9imuSnutSJyXMkUjc0OpOyB-qRxYcy5SzXa_BkXmbiX2gwWWptdiBVb7pvmk6ZugO-Ij1OXFc1RvqQQu8hymrXWvyO_kRg7scXnlmrrM1OiOXVpdoUvSZ76ZjRopOtOylJ0plwQa9vJ7kigu6XqRBeyW5xuJRc-oJ04Bhbjjgpm";

List driversList = [];
String? userDropOffAddress = "";
String driverCarDetails = "";
String driverName = "";
String driverPhone = "";

double countRatingStars = 0.0;
String titalRatingStars = "";
